version: 0.2

env:
  parameter-store:
    SONAR_TOKEN: "VPROFILE_SONARTOKEN"
    CODEARTIFACT_TOKEN: "CODEARTIFACT_TOKEN"
    HOST: "HOST"
    ORGANIZATION: "ORGANIZATION"
    SONAR_PROJECT: "SONAR_PROJECT"
    CODEARTIFACT_DOMAIN: "domain"
    CODEARTIFACT_OWNER: "domain-owner"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - mvn -version

  pre_build:
    commands:
      - echo "Preparing environment..."
      - echo "SONAR_PROJECT: $SONAR_PROJECT"
      - echo "ORGANIZATION: $ORGANIZATION"
      - echo "HOST: $HOST"
      - echo "SONAR_TOKEN: $SONAR_TOKEN"
      - echo "Environment setup completed."

  build:
    commands:
      - echo "Running SonarCloud analysis with Maven..."
      - mvn clean install -X
      - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
        -Dsonar.projectKey=$SONAR_PROJECT \
        -Dsonar.organization=$ORGANIZATION \
        -Dsonar.host.url=$HOST \
        -Dsonar.login=$SONAR_TOKEN

artifacts:
  files:
    - "**/*"
  discard-paths: yes

cache:
  paths:
    - "/root/.m2/**/*"
