version: 0.2
# AWS CodeBuild buildspec.yml for SonarCloud & AWS CodeArtifact (Maven)

env:
  variables:
    SONAR_HOST_URL: "https://sonarcloud.io"
    SONAR_ORG: "kubeirving-projects"
    SONAR_PROJECT: "vprofile-repo"
    CODEARTIFACT_TOKEN: "CODEARTIFACT_TOKEN"
    SONAR_TOKEN: "VPROFILE_SONARTOKEN"
    MAVEN_OPTS: "-Xmx2g"

phases:
  install:
    commands:
      - echo "Setting up Java 11...."
      - sudo apt-get update && sudo apt-get install -y openjdk-11-jdk maven unzip curl
      - java -version
      - mvn -version

      # Install Sonar Scanner
      - curl -sSLO https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
      - unzip sonar-scanner-cli-4.8.0.2856-linux.zip -d /opt
      - sudo mv /opt/sonar-scanner-4.8.0.2856-linux /opt/sonar-scanner
      - export PATH=$PATH:/opt/sonar-scanner/bin
      - echo 'export PATH=$PATH:/opt/sonar-scanner/bin' >> ~/.bashrc

      # Retrieve AWS CodeArtifact token
      - echo "Retrieving CODEARTIFACT_TOKEN from AWS SSM..."
      - CODEARTIFACT_TOKEN=$(aws ssm get-parameter --name "CODEARTIFACT_TOKEN" --query "Parameter.Value" --output text)
      - export CODEARTIFACT_TOKEN
      - echo "Token retrieved."

      # Authenticate with AWS CodeArtifact
      - echo "Retrieving AWS CodeArtifact authorization token..."
      - CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain visualpath --domain-owner 339712930264 --region us-east-1 --query authorizationToken --output text)
      - export CODEARTIFACT_AUTH_TOKEN
      - echo "AWS CodeArtifact token retrieved successfully."

      # Configure Maven to use CodeArtifact
      - echo "Configuring Maven settings for AWS CodeArtifact..."
      - mkdir -p ~/.m2
      - |
        cat > ~/.m2/settings.xml <<EOL
        <settings>
          <mirrors>
            <mirror>
              <id>aws-codeartifact</id>
              <mirrorOf>*</mirrorOf>
              <url>https://visualpath-339712930264.d.codeartifact.us-east-1.amazonaws.com/maven/vprofile-maven-repo/</url>
              <repositoryManager>true</repositoryManager>
            </mirror>
          </mirrors>
          <servers>
            <server>
              <id>aws-codeartifact</id>
              <username>aws</username>
              <password>${CODEARTIFACT_AUTH_TOKEN}</password>
            </server>
          </servers>
        </settings>
        EOL
      - echo "Maven configuration completed."

  pre_build:
    commands:
      - echo "Preparing for SonarCloud analysis..."

  build:
    commands:
      - echo "Building project with Maven..."
      - mvn clean install -DskipTests=true -X

      - echo "Running SonarCloud analysis..."
      - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey="$SONAR_PROJECT" \
          -Dsonar.organization="$SONAR_ORG" \
          -Dsonar.login="$SONAR_TOKEN" \
          -Dsonar.host.url="$SONAR_HOST_URL" \
          -Dsonar.codeartifact.token="$CODEARTIFACT_AUTH_TOKEN" \
          -Dsonar.java.jdkHome="/usr/lib/jvm/java-11-openjdk-amd64"

  post_build:
    commands:
      - echo "SonarCloud analysis complete."

artifacts:
  files:
    - target/*.jar

cache:
  paths:
    - '~/.m2/**/*'
