version: 0.2

env:
  variables:
    # SonarCloud properties are provided here as placeholders; include them if you later add Sonar analysis.
    SONAR_HOST_URL: "https://sonarcloud.io"
    SONAR_ORG: "newthiesco"
    SONAR_PROJECT: "vprofile"
    SONAR_TOKEN: "VPROFILE_SONARTOKEN"
    # CODEARTIFACT_TOKEN is not used directly; instead, we retrieve CODEARTIFACT_AUTH_TOKEN.
    CODEARTIFACT_TOKEN: "CODEARTIFACT_TOKEN"
    MAVEN_OPTS: "-Xmx2g"

phases:
  install:
    commands:
      - echo "Installing Java 8 and Maven..."
      - sudo apt-get update
      - sudo apt-get install -y openjdk-8-jdk maven
      - java -version
      - mvn -version

      - echo "Retrieving AWS CodeArtifact token..."
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain visualpath --domain-owner 339712930264 --region us-east-1 --query authorizationToken --output text)
      - echo "Token retrieved: $CODEARTIFACT_AUTH_TOKEN"

      - echo "Setting up Maven settings..."
      - mkdir -p ~/.m2
      - |
        cat > ~/.m2/settings.xml <<'EOF'
        <settings>
          <profiles>
            <profile>
              <id>visualpath-vprofile-maven-repo</id>
              <activation>
                <activeByDefault>true</activeByDefault>
              </activation>
              <repositories>
                <repository>
                  <id>visualpath-vprofile-maven-repo</id>
                  <url>https://visualpath-339712930264.d.codeartifact.us-east-1.amazonaws.com/maven/vprofile-maven-repo/</url>
                </repository>
              </repositories>
            </profile>
          </profiles>
          <servers>
            <server>
              <id>visualpath-vprofile-maven-repo</id>
              <username>aws</username>
              <password>$CODEARTIFACT_AUTH_TOKEN</password>
            </server>
          </servers>
          <mirrors>
            <mirror>
              <id>visualpath-vprofile-maven-repo</id>
              <name>visualpath-vprofile-maven-repo</name>
              <url>https://visualpath-339712930264.d.codeartifact.us-east-1.amazonaws.com/maven/vprofile-maven-repo/</url>
              <mirrorOf>*</mirrorOf>
            </mirror>
          </mirrors>
        </settings>
        EOF
      - echo "Maven settings.xml created:"
      - cat ~/.m2/settings.xml

  pre_build:
    commands:
      - echo "Pre-build phase: Confirming Maven settings..."
      - cat ~/.m2/settings.xml

  build:
    commands:
      - echo "Building the project with Maven..."
      - mvn clean install

  post_build:
    commands:
      - echo "Build completed. Artifacts in target/ directory:"
      - ls -l target/

artifacts:
  files:
    - target/*.war
  discard-paths: yes

cache:
  paths:
    - '~/.m2/**/*'
