version: 0.2

phases:
  install:
    runtime-versions:
      java: jdk17  # Use the appropriate Java version for your project
    commands:
      - echo "Installing dependencies..."
      - apt-get update && apt-get install -y jq  # Install jq for JSON parsing (optional)
      - echo "Maven version:"
      - mvn -version

  pre_build:
    commands:
      - echo "Pre-build phase: Downloading dependencies..."
      - mvn dependency:go-offline -B  # Download dependencies for offline use

  build:
    commands:
      - echo "Building the project with Maven..."
      - mvn clean package -DskipTests  # Build the project, skip tests for faster build

  post_build:
    commands:
      - echo "Post-build phase: Running SonarQube analysis..."
      - |
        mvn sonar:sonar \
          -Dsonar.projectKey=vprofile-repo8 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login="$VPROFILE_SONARTOKEN"

artifacts:
  files:
    - 'target/*.jar'  # Include only JAR files (adjust as needed)
    - 'target/*.war'  # Include only WAR files (adjust as needed)
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'  # Cache Maven dependencies for faster builds
