version: 0.2

env:
  variables:
    # SonarCloud configuration (optional)
    SONAR_HOST_URL: "https://sonarcloud.io"
    SONAR_ORG: "kubeirving-projects"  # Replace with your SonarCloud organization
    SONAR_PROJECT: "vprofile-repo"  # Replace with your SonarCloud project key
    SONAR_TOKEN: "VPROFILE_SONARTOKEN"  # Replace with your SonarCloud token
    MAVEN_OPTS: "-Xmx2g"  # Increase Maven memory limit
    CODEARTIFACT_TOKEN: "CODEARTIFACT_TOKEN"

phases:
  install:
    commands:
      # Install Java 8 (as specified in pom.xml)
      - echo "Installing Java 8..."
      - sudo apt-get update
      - sudo apt-get install -y openjdk-8-jdk maven unzip curl
      - java -version
      - mvn -version

      # Install Sonar Scanner (optional, for SonarCloud integration)
      - echo "Installing Sonar Scanner..."
      - curl -sSLO https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
      - unzip sonar-scanner-cli-4.8.0.2856-linux.zip -d /opt
      - sudo mv /opt/sonar-scanner-4.8.0.2856-linux /opt/sonar-scanner
      - export PATH=$PATH:/opt/sonar-scanner/bin
      - echo 'export PATH=$PATH:/opt/sonar-scanner/bin' >> ~/.bashrc

  pre_build:
    commands:
      # Optional: Print environment variables for debugging
      - echo "Java version:"
      - java -version
      - echo "Maven version:"
      - mvn -version
      - echo "Sonar Scanner version:"
      - sonar-scanner -v

  build:
    commands:
      # Build the project and run tests
      - echo "Building project and running tests..."
      - mvn clean install

      # Optional: Run SonarCloud analysis
      - echo "Running SonarCloud analysis..."
      - mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey="$SONAR_PROJECT" \
          -Dsonar.organization="$SONAR_ORG" \
          -Dsonar.host.url="$SONAR_HOST_URL" \
          -Dsonar.login="$SONAR_TOKEN"

  post_build:
    commands:
      # Optional: Print build artifacts
      - echo "Build artifacts:"
      - ls -l target/

artifacts:
  files:
    - target/*.war  # Package the WAR file as an artifact
  discard-paths: yes

cache:
  paths:
    - '~/.m2/**/*'  # Cache Maven dependencies for faster builds
