version: 0.2

phases:
  install:
    runtime-versions:
      java: jdk17
    commands:
      - echo "Installing dependencies..."
      - mvn -version

  build:
    commands:
      - echo "Building the project with Maven..."
      - mvn clean package -DskipTests
