version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Specify runtime version
      python: 3.9 # You can add multiple runtimes if needed
    commands:
      - echo Installing dependencies...
      - npm install -g aws-cli
      - pip install --upgrade pip
      - pip install some-python-package
  pre_build:
    commands:
      - echo Running pre-build steps...
      - aws --version
      - echo Logging into Docker...
      - $(aws ecr get-login-password --region us-east-1 | docker login --username thiexco --password-stdin 339712930264.dkr.ecr.us-east-1.amazonaws.com)
  build:
    commands:
      - echo Starting the build process...
      - npm run build
      - echo Building Docker image...
      - docker build -t my-app:latest .
      - docker tag my-app:latest 339712930264.dkr.ecr.us-east-1.amazonaws.com/my-app:latest
      - docker push 339712930264.dkr.ecr.us-east-1.amazonaws.com/my-app:latest
  post_build:
    commands:
      - echo Running post-build steps...
      - echo Build completed successfully!
      - echo Notifying stakeholders or performing cleanup...

artifacts:
  files:
    - "**/*"
  discard-paths: yes
  base-directory: build # Specify the directory containing the build output

