version: 0.2

env:
  variables:
    SONAR_HOST_URL: "HOST"
    SONAR_ORG: "ORGANIZATION"
    SONAR_PROJECT: "SONAR_PROJECT"
    SONAR_TOKEN: "VPROFILE_SONARTOKEN"
    CODEARTIFACT_TOKEN: "CODEARTIFACT_TOKEN"
    MAVEN_OPTS: "-Xmx2g"

phases:
  install:
    commands:
      - echo "Installing Java 8..."
      - sudo apt-get update
      - sudo apt-get install -y openjdk-8-jdk maven unzip curl
      - java -version
      - mvn -version

      - echo "Installing Maven..."
      - wget https://archive.apache.org/dist/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
      - tar -xzf apache-maven-3.8.8-bin.tar.gz -C /opt
      - export M2_HOME=/opt/apache-maven-3.8.8
      - export PATH=$M2_HOME/bin:$PATH
      - mvn -version

      - echo "Installing Sonar Scanner..."
      - curl -sSLO https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
      - unzip sonar-scanner-cli-4.8.0.2856-linux.zip -d /opt
      - sudo mv /opt/sonar-scanner-4.8.0.2856-linux /opt/sonar-scanner
      - export PATH=$PATH:/opt/sonar-scanner/bin
      - echo 'export PATH=$PATH:/opt/sonar-scanner/bin' >> ~/.bashrc

  pre_build:
    commands:
      - echo "Java version:"
      - java -version
      - echo "Maven version:"
      - mvn -version
      - echo "Sonar Scanner version:"
      - sonar-scanner -v

  build:
    commands:

      - echo "Adding SonarCloud repository..."
      - echo '<settings><mirrors><mirror><id>sonatype</id><url>https://repo.maven.apache.org/maven2</url><mirrorOf>central</mirrorOf></mirror></mirrors></settings>' > ~/.m2/settings.xml
      - echo "Building project and running tests..."
      - mvn clean install -U

      - echo "Running SonarCloud analysis..."
      - mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar -Dsonar.projectKey=$SONAR_PROJECT -Dsonar.organization=$SONAR_ORG -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN


  post_build:
    commands:
      - echo "Build artifacts:"
      - ls -l target/

artifacts:
  files:
    - target/*.war
  discard-paths: yes

cache:
  paths:
    - '~/.m2/**/*'
