version: 0.2

env:
  parameter-store:
    SONAR_TOKEN: "VPROFILE_SONARTOKEN"
    CODEARTIFACT_TOKEN: "CODEARTIFACT_TOKEN"
    HOST: "HOST"
    ORGANIZATION: "ORGANIZATION"
    SONAR_PROJECT: "SONAR_PROJECT"
    CODEARTIFACT_DOMAIN: "domain"
    CODEARTIFACT_OWNER: "domain-owner"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Java 17..."
      - java -version
  
  pre_build:
    commands:
      - echo "Preparing environment..."
      - aws --version
      - mvn --version
  
  build:
    commands:
      - echo "Running build and tests..."
      - mvn clean package
      - echo "Running SonarCloud analysis..."
      - |
        mvn sonar:sonar \
        -Dsonar.projectKey=${SONAR_PROJECT} \
        -Dsonar.organization=${ORGANIZATION} \
        -Dsonar.host.url=${HOST} \
        -Dsonar.login=${SONAR_TOKEN}

artifacts:
  files:
