version: 0.2
# Good buildspec.yml for AWS CodeBuild with SonarCloud & CodeArtifact

env:
  variables:
    SONAR_HOST_URL: "https://sonarcloud.io"  # SonarCloud URL
    SONAR_ORG: "kubeirving-projects"         # SonarCloud organization
    SONAR_PROJECT: "vprofile-repo"           # SonarCloud project
    CODEARTIFACT_TOKEN: "CODEARTIFACT_TOKEN" # SSM parameter for CodeArtifact token
    SONAR_TOKEN: "VPROFILE_SONARTOKEN"       # SonarQube token (best stored in AWS Secrets Manager)
    MAVEN_OPTS: "-Xmx2g"                     # Optimize Maven memory usage

phases:
  install:
    commands:
      - echo "Setting up Java 17..."
      - sudo apt-get update && sudo apt-get install -y openjdk-17-jdk maven unzip curl
      - java -version
      - mvn -version

      # Install Sonar Scanner (Only one version)
      - curl -sSLO https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
      - unzip sonar-scanner-cli-4.8.0.2856-linux.zip -d /opt
      - sudo mv /opt/sonar-scanner-4.8.0.2856-linux /opt/sonar-scanner
      - export PATH=$PATH:/opt/sonar-scanner/bin

      # Retrieve CodeArtifact token from AWS SSM
      - echo "Retrieving CODEARTIFACT_TOKEN from SSM..."
      - export CODEARTIFACT_TOKEN=$(aws ssm get-parameter --name "CODEARTIFACT_TOKEN" --query "Parameter.Value" --output text)

      # Authenticate with AWS CodeArtifact
      - echo "Authenticating with AWS CodeArtifact..."
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain visualpath --domain-owner 339712930264 --region us-east-1 --query authorizationToken --output text)
      - aws codeartifact login --tool maven --repository vprofile-maven-repo --domain visualpath --authorization-token $CODEARTIFACT_AUTH_TOKEN

  pre_build:
    commands:
      - echo "Preparing for SonarCloud analysis..."

  build:
    commands:
      - echo "Building project with Maven..."
      - mvn clean install -X

      - echo "Running SonarCloud analysis..."
      - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey="$SONAR_PROJECT" \
          -Dsonar.organization="$SONAR_ORG" \
          -Dsonar.login="$SONAR_TOKEN" \
          -Dsonar.host.url="$SONAR_HOST_URL" \
          -Dsonar.codeartifact.token="$CODEARTIFACT_AUTH_TOKEN" \
          -Dsonar.java.jdkHome="/usr/lib/jvm/java-17-openjdk-amd64"

  post_build:
    commands:
      - echo "SonarCloud analysis complete."

artifacts:
  files:
    - target/*.jar  # Adjust based on your build artifacts

cache:
  paths:
    - '/root/.m2/**/*'  # Cache Maven dependencies to speed up builds
